//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivitySystem.PL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Home_Index_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Home_Index_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActivitySystem.PL.Resources.Views.Home.Index.en", typeof(Views_Home_Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			Excellence in teaching and learning, well-defined, community-aware, through the principles of scientific integration and creative thinking in a stimulating academic environment, participation in the production and dissemination of knowledge, and interaction with local communities.
        ///        .
        /// </summary>
        internal static string mission {
            get {
                return ResourceManager.GetString("mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        internal static string subtitle {
            get {
                return ResourceManager.GetString("subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			Mission
        ///        .
        /// </summary>
        internal static string subtitle2 {
            get {
                return ResourceManager.GetString("subtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision and Mission.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///			That the university maintain its pioneering role in the field of university education for the community within the Sultanate, and that the classical sciences be distinguished by its scouting research, its graduates, and its strategic partnerships.
        ///        .
        /// </summary>
        internal static string vision {
            get {
                return ResourceManager.GetString("vision", resourceCulture);
            }
        }
    }
}
